apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-dev
data:
  USER: root
  DATABASE_URL: mysql://10.100.1.251:3306/SpringWebYoutube?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
