- hosts: all
  become: yes
  tasks:
    - name: "Upload k8s-deploy"
      copy:
        src: "k8s-deploy"
        dest: "~/"

    - name: "Aplicar configmap"
      become: yes
      shell: kubectl apply -f ~/k8s-deploy/mysql-configmap-'{{ environment }}'.yml

    - name: "Aplicar secret"
      become: yes
      shell: kubectl apply -f ~/k8s-deploy/mysql-secret.yml

    - name: "Aplicar deployment"
      become: yes
      shell: kubectl apply -f ~/k8s-deploy/deployment-'{{ environment }}''.yml

    - name: "Aplicar nodeport"
      become: yes
      shell: kubectl apply -f ~/k8s-deploy/nodeport-javadb-'{{ environment }}''.yml

    - shell: "kubectl get pods | grep java-deployment-'{{ environment }}'"
      become: yes
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
