pipeline {
    agent any

    parameters {
        string(name: 'ami_id', defaultValue: '', description: 'Digite o ID da AMI que será utilizad para o deploy')
    } 
    stages {
        stage('Git Checkout') {
            steps {
                git credentialsId: 'git-ssh-private-key',
                    url: 'git@github.com:Auto-Mates-TCC-Doti-2-0/grupo7-turma3-desafio-final.git', 
                    branch: 'main'
            }
        }
        stage("Prepara infra para o cluster K8S multi-master") {
            steps {
                echo "construindo o cluster terraform utilizando a ami ${ami_id}"
                sh " 03-k8s-multi-master/deploy.sh"
            }
        }
        stage("Testa estado dos master e worker nodes") {
            steps {
                echo "Validando status dos nodes"
                test_out = sh(returnStdout: true, script: "03-k8s-multi-master/teste.sh")
                if ( test_out.contains("ERRO") ) {
                    error("${test_out}")
                }
            }
        }
    }
}